name: Aperture f16, Sunny Exposure
markdown: kramdown

baseurl: /aperturef16/
domain_name: 'https://artneldy.github.io'

permalink: /blog/:year/:month/:day/:title
exlude:

collections:
  modules:
    output:
  courses:
    output:

include:
- _stylesheets

lang: en
